[tool.poetry]
name = "text-to-speech"
version = "0.1.0"
description = ""
authors = ["Alen Vlahovljak <alen.vlahovljak@evolt.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
gTTS = "^2.2.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
